name: front
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  footer:
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.5
  flutter_rating_bar: ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.0
  http: ^1.2.1
  size_config: ^2.0.3
  flutter_signin_button: ^2.0.0
  sign_button: ^2.0.3
  local_captcha: ^1.0.1
  go_router: ^14.0.2
  binding: ^1.0.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.1.4
  vector_math: ^2.1.4
  simple_3d_renderer: ^19.1.0
  simple_3d: ^13.1.1
  util_simple_3d: ^9.0.0
  path: ^1.8.2
  tuple: ^2.0.2
  provider: ^6.1.1
  jwt_decoder: ^2.0.1
  fluttertoast: ^8.2.4
  flutter_stripe: ^10.1.1
  flutter_stripe_web: ^5.1.0
  file_picker: ^8.0.3
  shared_preferences: ^2.2.2
  mockito: ^5.4.0
  flutter_dropzone: ^4.0.0
  dotted_border: ^2.1.0
  sizer: ^2.0.15
  google_maps_flutter: ^2.3.0
  geolocator: ^11.0.0
  image_picker: ^0.8.4+8
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.2
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google.png
    - assets/logo.png
    - assets/logonew.png
    - assets/google-logo.png
    - assets/iphone.png
    - assets/iphonenew.png
    - assets/container.png
    - assets/3d_logo.png
    - assets/cube.png
    - assets/Henri.png
    - assets/Louis.png
    - assets/Hugo.png
    - assets/Quentin.png
    - assets/Tanguy.png
    - assets/Cédric.png
    - assets/containerrisu.png
    - assets/roboto/Roboto-Medium.ttf

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rozha
      fonts:
        - asset: fonts/Rozha.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
