#!/bin/bash

run ()
{
  flutter run
}

apk () {
  flutter build apk
  cp build/app/outputs/flutter-apk/app-release.apk .
}

remote ()
{
  sudo adb kill-server
  sudo adb start-server
  adb tcpip 5555
  # shellcheck disable=SC2046
  adb connect $(adb shell ip route | awk '{print $9}'):5555
}

integration_tests ()
{
  flutter test test/*_test.dart --coverage
  genhtml coverage/lcov.info -o coverage/html
  xdg-open coverage/html/index.html
}

if [ "$1" == "" ]; then
    run
elif [ "$1" == "tests" ]; then
    integration_tests
elif [ "$1" == "ios" ]; then
    ios
elif [ "$1" == "remote" ]; then
    remote
elif [ "$1" == "apk" ]; then
    apk
else
    echo "Unknown command."
fi