// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR8O2Z18SYCnpNBx618HQl_IrxPwfuut4',
    appId: '1:832804007349:web:6ab2c181fd8f25a526bdfc',
    messagingSenderId: '832804007349',
    projectId: 'deeplink-risu',
    authDomain: 'deeplink-risu.firebaseapp.com',
    storageBucket: 'deeplink-risu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ2hvpa0o6mCLOXfjuU8L2TZ72zyEDQgs',
    appId: '1:832804007349:android:a7f7abfdcec62ff126bdfc',
    messagingSenderId: '832804007349',
    projectId: 'deeplink-risu',
    storageBucket: 'deeplink-risu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFAjsMI19xfqJ16V5MtTe3jvGHI08A_Ww',
    appId: '1:832804007349:ios:330e6e370c5d47cd26bdfc',
    messagingSenderId: '832804007349',
    projectId: 'deeplink-risu',
    storageBucket: 'deeplink-risu.firebasestorage.app',
    iosClientId:
        '832804007349-mvrpqijg8cf1lnc1obvtsvf20k746k33.apps.googleusercontent.com',
    iosBundleId: 'com.example.risu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFAjsMI19xfqJ16V5MtTe3jvGHI08A_Ww',
    appId: '1:832804007349:ios:330e6e370c5d47cd26bdfc',
    messagingSenderId: '832804007349',
    projectId: 'deeplink-risu',
    storageBucket: 'deeplink-risu.firebasestorage.app',
    iosClientId:
        '832804007349-mvrpqijg8cf1lnc1obvtsvf20k746k33.apps.googleusercontent.com',
    iosBundleId: 'com.example.risu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR8O2Z18SYCnpNBx618HQl_IrxPwfuut4',
    appId: '1:832804007349:web:6274c781f934e40526bdfc',
    messagingSenderId: '832804007349',
    projectId: 'deeplink-risu',
    authDomain: 'deeplink-risu.firebaseapp.com',
    storageBucket: 'deeplink-risu.firebasestorage.app',
  );
}
