version: "3.2"

services:
  database:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    env_file:
      - .env
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "mysql-data:/var/lib/mysql"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]

  server:
    build:
      context: ./back
    container_name: server
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    restart: always
  web_app:
    build:
      context: ./front
    ports:
      - 80:5000

volumes:
  mysql-data:
