name: Code quality check

on: push

jobs:
  Prettier-WEB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: dart-lang/setup-dart@v1

      - name: Test
        working-directory: ./Configurateur/front/
        run: |
          flutter pub get
          dart format --output=none --set-exit-if-changed ./lib/**/*
