name: Code quality check

on: push

jobs:
  Prettier-WEB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download dependencies
        run: |
        npm i prettier-plugin-dart
        npm i prettier
      - name: run prettier
        run: |
          npx prettier -c './Configurateur/front/lib/**/*'
