name: Code quality check

on: push

jobs:
  Prettier-WEB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed ./Configurateur/front/lib/**/*
