name: Create envfile

on: [ push ]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        directory: Configurateur/back/
        file_name: .env
        fail_on_empty: false

name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  WEB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose
      - name: Start Docker Compose
        working-directory: ./Configurateur
        run: docker-compose up -d
      - name: Verify Docker Compose
        working-directory: ./Configurateur
        run: docker-compose ps
      - name: Stop Docker Compose
        working-directory: ./Configurateur
        run: docker-compose down
