name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  WEB-BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose
      - name: Start Docker Compose
        working-directory: ./Configurateur
        run: docker-compose up -d
      - name: Verify Docker Compose
        working-directory: ./Configurateur
        run: docker-compose ps
      - name: Stop Docker Compose
        working-directory: ./Configurateur
        run: docker-compose down
  WEB-TEST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Run unit tests (WEB)
        working-directory: ./Configurateur/front
        run: flutter test
  MOBILE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose
      - name: Start Docker Compose
        working-directory: ./Application
        run: docker-compose up -d
      - name: Verify Docker Compose
        working-directory: ./Application
        run: docker-compose ps
      - name: Stop Docker Compose
        working-directory: ./Application
        run: docker-compose down
  MOBILE-TEST:
      runs-on: macos-11
      strategy:
        matrix:
          api-level:
            - 29
        fail-fast: true
      steps:
        - uses: actions/checkout@v3
        - name: Setup Flutter SDK
          uses: subosito/flutter-action@v2
          with:
            channel: stable
        - name: Install Flutter dependencies
          working-directory: ./Application/mobile/app_code
          run: flutter pub get
        - name: Run integration tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: ${{ matrix.api-level }}
            arch: x86_64
            profile: Nexus 6
            script: ./run it
